---
- name: Install X Window System with yum
  ansible.builtin.yum:
    name: "@X Window System"
    state: present

- name: Install GNOME Desktop with yum
  ansible.builtin.yum:
    name:
      - gnome-classic-session
      - gnome-terminal
      - control-center
      - liberation-mono-fonts
    state: present

- name: Install ibus-kkc（a Japanese Kana Kanji input engine for IBus）with yum
  ansible.builtin.yum:
    name: ibus-kkc
    state: present

- name: Install VL Gothic Font Family with yum
  ansible.builtin.yum:
    name: vlgothic-*
    state: present

- name: Install TigerVNC Server with yum
  ansible.builtin.yum:
    name: 'tigervnc-server'
    state: present

- name: Check whether configuration file is created
  ansible.builtin.command: test -e /etc/systemd/system/vncserver@:1.service
  register: configfile_exists
  changed_when: False
  ignore_errors: True

- name: Copy configuration file
  ansible.builtin.copy:
    src: /lib/systemd/system/vncserver@.service
    dest: /etc/systemd/system/vncserver@:1.service
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  when: configfile_exists is failed

- name: Configure connecting user settings
  ansible.builtin.replace:
    dest: /etc/systemd/system/vncserver@:1.service
    regexp: '<USER>'
    replace: "{{ vnc_user }}"

- name: Add VNC user to system
  ansible.builtin.user:
    name: "{{ vnc_user }}"
    password: "{{ vnc_password }} | password_hash('sha512')"

- name: Create $HOME/.vnc directory
  ansible.builtin.file:
    path: "/home/{{ vnc_user }}/.vnc"
    state: directory
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0755

- name: Check whether vnc password is set
  ansible.builtin.command: "test -e /home/{{ vnc_user }}/.vnc/passwd"
  register: vncpassword_set
  changed_when: False
  ignore_errors: True

- name: Set default password
  ansible.builtin.shell: |
    set -o pipefail
    echo {{ vnc_password }} | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd
  when: vncpassword_set is failed

- name: Change permission of password settings file
  ansible.builtin.file:
    path: "/home/{{ vnc_user }}/.vnc/passwd"
    state: file
    owner: '{{ vnc_user }}'
    group: '{{ vnc_user }}'
    mode: 0600

- name: Start and enable VNC server
  ansible.builtin.systemd:
    name: vncserver@:1.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
