---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "docker.pkg.github.com/docker-hub-tm/ansible-test/${MOLECULE_DISTRO:-centos7}:latest"
    registry:
      url: docker.pkg.github.com
      credentials:
        username: ${GITHUB_PACKAGES_USERNAME}
        password: ${GITHUB_PACKAGES_PASSWORD}
    pre_build_image: True
    command: /sbin/init
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
