---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether VNC Server installed
      ansible.builtin.command: vncserver -help
      register: vncserver_installed
      changed_when: false
      ignore_errors: True

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure VNC Server is installed
      ansible.builtin.debug:
        var: vncserver_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
